AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  discounted-product-service

  SAM Template for mock discounted-product-service
Parameters:
  AllowedOrigin:
    Type: "String"

Globals:
  Function:
    Timeout: 5
    Tracing: Active
    AutoPublishAlias: live
    Runtime: python3.8
    MemorySize: 256
    Environment:
      Variables:
        LOG_LEVEL: "DEBUG"
        ALLOWED_ORIGIN: !Ref AllowedOrigin
        POWERTOOLS_SERVICE_NAME: discounted-product-mock
        POWERTOOLS_METRICS_NAMESPACE: ecommerce-app
  Api:
    EndpointConfiguration: REGIONAL
    TracingEnabled: true
    OpenApiVersion: "2.0"
    Cors:
      AllowMethods: "'OPTIONS,POST,GET'"
      AllowHeaders: "'Content-Type,Authorization,authorization'"
      AllowOrigin: !Sub "'${AllowedOrigin}'"
Resources:
  GetDiscountedProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: discounted-product-mock-service/
      Handler: get_discounted_products.lambda_handler
      Events:
        ListCart:
          Type: Api
          Properties:
            Path: /discounted_product
            Method: get

  GetDiscountedProductApiUrl:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: /serverless-shopping-cart-demo/discounted_products/discounted-products-api-url
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"

Outputs:
  DiscountedProductApi:
    Description: "API Gateway endpoint URL for Prod stage for Discounted Product Mock Service"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
